language: julia

branches:
  only:
  - master

os:
  - linux
  - osx
  - windows

julia:
  - 1.5
  - nightly

notifications:
  email: false

cache:
  directories:
    - /home/travis/.julia/

jobs:
  allow_failures:
    - julia: nightly
#   include:
#     - stage: "Documentation"
#       julia: 1.5
#       os: linux
#       script:
#         - julia --project=docs/ -e '
#             using Pkg;
#             Pkg.develop(PackageSpec(path=pwd()));
#             Pkg.build();
#             Pkg.instantiate();'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
